services:
  github-actions:
    statuspage: https://www.githubstatus.com
    status_page_specific: Actions
    subreddits: [github, devops]
    keyword: "github actions"
    keywords: ["stuck in queued", "runners not picking up"]
    github_repos: [actions/runner-images, actions/runner]
    bluesky_queries: ["github actions down"]
    hackernews_queries: ["github actions down"]
  gitlab:
  codeberg:
  artifactory:
  aws:
  gcp:
  azure:
  ibm-cloud:
  okta:
  terraform-cloud:
  hcp:
  vault:
  prometheus:
  datadog:
  jira:
  incident.io:
  pagerduty:
  npm:
    statuspage: https://status.npmjs.org/
  datadog:
